### ISSUE TITLE
Kick message doesn't show up when you kick after calling server.Accept()

### ISSUE THREAD

**Issue by Arcoz0308** [df-mc/dragonfly#251]
when you kick someone directly after accept to join the message doesn't show up

**Comment by Sandertv** [comment]
Postponing to v0.5.0.

**Comment by Sandertv** [comment]
This issue doesn't just occur directly after joining, but also occasionally afterwards. It happens more frequently because the client is sent more packets during the login sequence, causing it to take longer to handle the Disconnect packet. Contrarily, it seems to handle the RakNet disconnect notification immediately regardless of any Minecraft packets (probably on another thread?). This leads to the client handling the disconnect notification before the Disconnect packet, causing the message not to show up.
