### ISSUE TITLE
Teleporting right after world change does not work

### ISSUE THREAD

**Issue by AndreasHGK** [df-mc/dragonfly#272]
Whenever I change a player's world and teleport them somewhere right after this world change, nothing seems to happen at all. If I teleport the player first and then change the world the player does get teleported

My platform is windows 10 and i used the latest commit

**Comment by T14Raptor** [comment]
Probably related to #237

**Comment by Sandertv** [comment]
So I think the issue here is that `*Player.Teleport()` loops through all viewers and sends them the teleportation. However, if you switch worlds, the goroutine that loads chunks in `session.sendChunks` only updates the place it's viewing every tick, meaning it won't yet be viewing the position of the player in the new world. While a simple `p.session().ViewEntityTeleport` would fix this, I think more issues might pop up if we don't make sessions view the new world immediately. We should probably explore that solution.
