### ISSUE TITLE
Double deaths sometimes happening on death

### ISSUE THREAD

**Issue by T14Raptor** [df-mc/dragonfly#657]

**Comment by Sandertv** [comment]
I'm inclined to believe this might be fixed by this commit: https://github.com/df-mc/dragonfly/compare/480ad722834e...eec10b7e7b59

I think I remember you guys doing checks to see if FinalDamageFrom() would result in the player dying. This would be the case sometimes because a random value was used in there, even though the actual damage wouldn't kill the player.
