### ISSUE TITLE
Visual glitching

### ISSUE THREAD

**Issue by ItsZodiaX** [df-mc/dragonfly#672]
The videos of visual glitching (chunk flushing)

https://cdn.discordapp.com/attachments/863752747571609610/1025041897493897316/2022-09-29_20-39-20_Trim.mp4
https://cdn.discordapp.com/attachments/863752747571609610/1025043240669417563/2022-09-29_20-51-28_Trim.mp4

**Comment by JustTalDevelops** [comment]
This is more-so a Minecraft issue rather than an issue with Dragonfly. You can try to offset the worlds at different positions so that chunks will smoothly load in no matter what world you try to join, but there isn't a whole lot more you can do to tell the client to flush chunks between the same dimension.
