### ISSUE TITLE
Add compression algorithm, level, threshold configuration

### ISSUE THREAD

**Issue by AkmalFairuz** [df-mc/dragonfly#698]

**Comment by AkmalFairuz** [comment]
> Why do you think this should be added to Dragonfly? We'll need some more motivation for that.

- Currently Dragonfly uses snappy compression algorithm. I do not want to use snappy because snappy does not support compression level
- Compress every packets is useless so Dragonfly should have a compression threshold (only compress large packets)
- Increasing the compression level can save bandwidth usage (although not so significant)
- Decreasing the compression level to decrease CPU usage and make the proxy decompress fast.

**Comment by Sandertv** [comment]
First of all, Dragonfly does not currently use snappy compression because it isn't reliable client-side.

I would then like to ask you if you have any specific reason to do this? Has there been any performance issue you've run into? If not, I don't really see a reason for adding configuration for this. I would much rather investigate settings that work well in all circumstances.

I would also like to explain that Snappy is *considerably* faster than zlib, so if you're doing this for performance reasons, snappy is going to be the way to go no matter what.

**Comment by JustTalDevelops** [comment]
I don't really think this proposal has much purpose, to be honest. To the average user, compression should and will be irrelevant. Snappy right now is currently broken for various devices, so switching compression algorithms doesn't really make sense. Level and threshold, maybe, but at that point we might as well wait until Snappy gets fixed and then support that instead; it'll be far faster than any configuration of zlib that we can use.
